//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acesso
    {
        public long id_acesso { get; set; }
        public Nullable<long> id_pessoa { get; set; }
        public Nullable<long> id_veiculo { get; set; }
        public long id_ponto_acesso { get; set; }
        public Nullable<System.TimeSpan> horario_ini { get; set; }
        public Nullable<System.TimeSpan> horario_fim { get; set; }
        public bool permitido { get; set; }
        public int rele { get; set; }
    
        public virtual pessoa pessoa { get; set; }
        public virtual veiculo veiculo { get; set; }
    }
}
