//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contexto : DbContext
    {
        public Contexto()
            : base("name=BD_Controller_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acesso> acessoes { get; set; }
        public virtual DbSet<pessoa> pessoas { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<tipo_pessoa> tipo_pessoa { get; set; }
        public virtual DbSet<veiculo> veiculos { get; set; }
        public virtual DbSet<tipo_dedo> tipo_dedo { get; set; }
        public virtual DbSet<documento> documentos { get; set; }
        public virtual DbSet<dedo> dedos { get; set; }
    }
}
