//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pessoa()
        {
            this.acessoes = new HashSet<acesso>();
            this.veiculos = new HashSet<veiculo>();
            this.documentos = new HashSet<documento>();
            this.dedos = new HashSet<dedo>();
        }
    
        public long id_pessoa { get; set; }
        public long id_tipo_pessoa { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public byte[] foto { get; set; }
        public Nullable<long> old_id { get; set; }
        public Nullable<System.DateTime> dt_ini_val { get; set; }
        public Nullable<System.DateTime> dt_fim_val { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acesso> acessoes { get; set; }
        public virtual tipo_pessoa tipo_pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<veiculo> veiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dedo> dedos { get; set; }
    }
}
