//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veiculo()
        {
            this.acessoes = new HashSet<acesso>();
        }
    
        public long id_veiculo { get; set; }
        public Nullable<long> id_pessoa { get; set; }
        public long id_tipo_veiculo { get; set; }
        public Nullable<long> id_marca { get; set; }
        public Nullable<long> id_modelo { get; set; }
        public string cor { get; set; }
        public string placa { get; set; }
        public byte[] foto { get; set; }
        public Nullable<long> old_id { get; set; }
        public Nullable<System.DateTime> dt_ini_val { get; set; }
        public Nullable<System.DateTime> dt_fim_val { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acesso> acessoes { get; set; }
        public virtual pessoa pessoa { get; set; }
    }
}
